name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Descarga el código de tu repo
      - uses: actions/checkout@v3

      # Configura Node.js versión 18
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Instala dependencias
      - run: npm install

      # Ejecuta el build de tu app (ajusta si tu script se llama diferente)
      - run: npm run build
